autodemi/contents/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class ContentForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    link = StringField('Link', validators=[DataRequired()])
    description = TextAreaField('Content', validators=[])
    add = SubmitField('Add')

autodemi/contents/routes.py
from flask import (render_template, url_for, flash, redirect, request, abort, jsonify, Blueprint)
from flask_login import current_user, login_required
from autodemi import db
from autodemi.models import Content, UserLibrary
from autodemi.contents.forms import ContentForm
from sqlalchemy import and_
from autodemi.contents.helper import *



contents = Blueprint('contents', __name__)



@contents.route("/content/add", methods=['GET', 'POST'])
@login_required
def add_content():
    form = ContentForm()
    if form.validate_on_submit():
        image_file = screenshot_site(form.link.data)
        link = process_url(form.link.data)
        content = Content(title=form.title.data, link=link, image_file=image_file, description=form.description.data, creator=current_user)
        db.session.add(content)
        db.session.commit()
        flash('The content has been added to our database!', 'success')
        return redirect(url_for('main.home'))
    return render_template('add_content.html', title='Add Content',
                            form=form, legend='Add Content')

@contents.route("/content/user_interaction", methods=['POST'])
def content_user_interaction():
    if not current_user.is_authenticated:
        return jsonify(message="redirect", target=url_for('users.login'))

    button_id = request.form['button_id'].split('-')[0]
    button_id = "".join([x for x in button_id if not x.isdigit()])
    button_context = request.form['button_id'][len(button_id):]
    content_id = int(request.form['content_id'])

    record = UserLibrary.query.filter(and_(UserLibrary.content_id==content_id, UserLibrary.user_id==current_user.id)).first()

    if record:
        if button_id == 'add_to_library':
            db.session.delete(record)
            to_return = []
        else:
            setattr(record, button_id, not getattr(record, button_id))
            to_return = record
    else:
        new_library_content = UserLibrary(user_id=current_user.id, content_id=content_id, consumed=False, to_consume=False, consuming=False, star=False)
        if button_id != 'add_to_library':
            setattr(new_library_content, button_id, not getattr(new_library_content, button_id))
        db.session.add(new_library_content)
        to_return = new_library_content

    to_return = content_interactions_html_dict(to_return)
    db.session.commit()
    return jsonify(message="success", interactions=to_return, button_context=button_context)


@contents.route("/content/<int:content_id>")
def content(content_id):
    content = Content.query.get_or_404(content_id)
    interaction = UserLibrary.query.filter(and_(UserLibrary.content_id==content.content_id, UserLibrary.user_id==current_user.id)).first()
    content = [content, content_interactions_html_dict(interaction)]
    return render_template('content.html', content=content)


@contents.route("/content/delete", methods=['POST'])
@login_required
def delete_content():
    if not current_user.is_authenticated:
        return jsonify(message="redirect", target=url_for('users.login'))

    content_id = int(request.form['content_id'])
    content = Content.query.get_or_404(content_id)
    if content.creator != current_user:
        abort(403)
    interactions = UserLibrary.query.filter(UserLibrary.content_id==content.content_id).all()
    for interaction in interactions:
        db.session.delete(interaction)
    db.session.delete(content)


    db.session.commit()
    flash('Your content has been deleted!', 'success')
    return jsonify(message="redirect", target=url_for('main.home'))

autodemi/main/routes.py
from flask import render_template, request, Blueprint
from flask_login import current_user
from autodemi.models import Content, UserLibrary
from sqlalchemy import and_
from autodemi.contents.helper import content_interactions_html_dict


main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', default=1, type=int)
    content_per_page = 4
    contents = Content.query.order_by(Content.date_added.desc()).paginate(page=page, per_page=content_per_page)
    page_obj = contents
    buttons_info = []
    user_info = []
    if current_user.is_authenticated:
        for content in contents.items:
            interactions = UserLibrary.query.filter(and_(UserLibrary.content_id==content.content_id, UserLibrary.user_id==current_user.id)).first()
            user_info.append(interactions)
        for i in range(len(user_info)):
            buttons_list = content_interactions_html_dict(user_info[i])
            buttons_info.append(buttons_list)

    else:
        for i in range(len(contents.items)):
            buttons_list = {'consuming': False, 'star': False, 'to_consume': False, 'consumed': False, 'add_to_library': False}

            for k in buttons_list:
                if buttons_list[k]:
                    buttons_list[k] = "content-library-button-selected"
                else:
                    buttons_list[k] = "content-library-button-unselected"
            buttons_info.append(buttons_list)
    contents = zip(contents.items, buttons_info)
    return render_template('home.html', contents=contents, page_obj=page_obj)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

autodemi/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from autodemi import db, bcrypt
from autodemi.models import User, Content, UserLibrary
from autodemi.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm)
from autodemi.users.helper import save_picture, send_reset_email
from autodemi.contents.helper import content_interactions_html_dict


users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)




@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/user/<string:username>")
def user_profile(username):
    #page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    library_content = UserLibrary.query.filter(UserLibrary.user_id==user.id).all()

    content = []
    for lib_c in library_content:
        content.append([lib_c.content, content_interactions_html_dict(lib_c)])


    #posts = Post.query.filter_by(author=user)\
    #    .order_by(Post.date_posted.desc())\
    #    .paginate(page=page, per_page=5)
    return render_template('user_profile.html', library=content, user=user)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

autodemi/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

autodemi/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

autodemi/templates/add_content.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.link.label(class="form-control-label") }}
                {% if form.link.errors %}
                    {{ form.link(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.link.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.link(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.description.label(class="form-control-label") }}
                {% if form.description.errors %}
                    {{ form.description(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.description.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.description(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.add(class="btn btn-outline-info", id="btn", onclick="disableField()") }}
        </div>
    </form>
</div>
<script>
function disableField() {
  //document.getElementById('btn').disabled = true;
};
</script>

{% endblock content %}
, data-loading-text="<i class='fa fa-spinner fa-spin '></i> Processing Order"

autodemi/templates/content.html
{% extends "layout.html" %}
{% block content %}
    {% set loop_index = 1 %}
    {% set context = 'content' %}
    {% include 'content_layout.html' %}
{% endblock content %}

autodemi/templates/content_layout.html
<article class="media content-section">
  <div class="media-body">
    <div class="content-metadata">
      <img class="rounded-circle article-img content-profile-pic" src="{{ url_for('static', filename='profile_pics/' + content[0].creator.image_file) }}">
      <div class="content-username-datetime">
        <a class="mr-2" href="{{ url_for('users.user_profile', username=content[0].creator.username) }}">{{ content[0].creator.username }}</a>
        <small class="text-muted content-datetime">{{ content[0].date_added.strftime('%Y-%m-%d') }}</small>
      </div>
      <div class="content-library-buttons-div">
        {% set b_app = loop_index|string ~ '-' ~ context  %}
        <button type="button" id="{{ 'consuming' ~ b_app  }}" 
          class="btn btn-default content-library-button {{ content[1]['consuming'] }}" 
          onClick="{{ 'contentInteraction(this.id, ' ~ content[0].content_id|string ~ ')' }}" aria-label="Consuming">
          <i class="fa fa-retweet" aria-hidden="true"></i>
        </button>

        <button type="button" id="{{ 'star' ~ b_app }}" 
          class="btn btn-default content-library-button {{ content[1]['star'] }}" 
          onClick="{{ 'contentInteraction(this.id, ' ~ content[0].content_id|string ~ ')' }}""contentInteraction(this.id)" aria-label="Add To Library">
          <i class="fa fa-star-o" aria-hidden="true"></i>
        </button>
        <button type="button" id="{{ 'to_consume' ~ b_app }}""to_consume" 
          class="btn btn-default content-library-button {{ content[1]['to_consume'] }}" 
          onClick="{{ 'contentInteraction(this.id, ' ~ content[0].content_id|string ~ ')' }}" aria-label="To Consume">
          <i class="fa fa-clock-o" aria-hidden="true"></i>
        </button>
        <button type="button" id="{{ 'consumed' ~ b_app }}" 
          class="btn btn-default content-library-button {{ content[1]['consumed'] }}" 
          onClick="{{ 'contentInteraction(this.id, ' ~ content[0].content_id|string ~ ')' }}" aria-label="Consumed">
          <i class="fa fa-check" aria-hidden="true"></i>
        </button>
        <button type="button" id="{{ 'add_to_library' ~ b_app }}" 
          class="btn btn-default content-library-button {{ content[1]['add_to_library'] }}" 
          onClick="{{ 'contentInteraction(this.id, ' ~ content[0].content_id|string ~ ')' }}" aria-label="Add To Library">
          <i class="fa fa-plus" aria-hidden="true"></i>
        </button>
        <button type="button" id="{{ 'options' ~ b_app }}" data-toggle="dropdown"
          class="btn btn-default options-button">
          <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
        </button>
          <ul class="dropdown-menu">
            <li role="presentation" >
              <a class="btn {% if current_user.is_authenticated %}{% if not (content[0].creator.id==current_user.id) %}{{'disabled'}}{% endif %}{% endif %}" href="#" onclick="{{ 'deleteContent(' ~ content[0].content_id|string ~ ');return false;' }}">delete</a>
            </li>
          </ul>
      </div>
    </div>
    <h3><a class="content-title" href="{{ url_for('contents.content', content_id=content[0].content_id) }}">{{ content[0].title }}</a></h3>
    <div class="content-description-div">
      <p class="content-description">{{ content[0].description }}</p>
    </div>
    {% if "https://www.youtube." in content[0].link and "embed/" in content[0].link %}
      <div class="content-video-container">
        <iframe class="content-video" allowfullscreen="allowfullscreen"
          src={{content[0].link}}>
        </iframe> 
      </div>
    {% else %}
      <a class="content-image-link" href="{{ content[0].link }}" target="_blank">
      <img class="content-image" src="{{ url_for('static', filename='site_pics/' + content[0].image_file) }}"/>
      </a>
      <p class="content-link"><a class="link" href="{{ content[0].link }}" target="_blank">link<a></p>
    {% endif%}
  </div>
</article>

autodemi/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for content in contents %}
        {% set loop_index = loop.index %}
        {% set context = 'home'%}
        {% include 'content_layout.html' %}
    {% endfor %}
    {% for page_num in page_obj.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if page_obj.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

autodemi/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Autodemi - {{ title }}</title>
    {% else %}
        <title>Autodemi</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-lg navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Autodemi</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('contents.add_content') }}">Add Content</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Sign out <i class="fa fa-sign-out" aria-hidden="true"></i>
</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>




    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='interactive.js')}}"></script>

</body>
</html>

autodemi/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

autodemi/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}

autodemi/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}